### ISSUE TITLE
HyBid Ad Load interferes with AVPlayer Playback

### ISSUE THREAD

**Issue by wimbledon** [pubnative/pubnative-hybid-ios-sdk#228]
I found a very strange issue that only occurs in iPhone XR but not the iPhone 5s or possibly lower spec devices. 
Also, the problem does not occur on Xcode Simulator.

iOS 13.5
Xcode: 11.4.1
HyBid SDK: 1.5.1

The issue is that, if the following code is executed while the AVPlayer is playing, the AVPlayer will pause.
This is a critical issue for any music or video player app because of the HyBid ad loading interferes with playback.
```
HyBidAdView *adView; 
[adView loadWithZoneID:_id andWithDelegate:self];
```

**Comment by can-soykarafakili** [comment]
Hey @wimbledon !!

Thank you for noticing and informing us about the issue. We've released a new version of [HyBid iOS SDK v:1.5.2](https://github.com/pubnative/pubnative-hybid-ios-sdk/releases/tag/1.5.2) which fixes the bug.

Feel free to contact with us for further questions/issues.

Happy coding!! 😄

**Comment by wimbledon** [comment]
Wow, @can-soykarafakili.
Thank you for resolving this bug so quickly!

Just curious, what was the issue that only causes this bug in the device but not in the simulator?

**Comment by can-soykarafakili** [comment]
Yes @wimbledon you are correct. 👍  We are enriching our ad request with device information in this case if the device is muted or not. We are retrieving that information `AVAudioSession`. For some reason, `AVAudioSession` did not interfere the `AVPlayer` in the simulator. 🤔
