### ISSUE TITLE
UIWebView Dependency

### ISSUE THREAD

**Issue by wimbledon** [pubnative/pubnative-hybid-ios-sdk#318]
The pubnative SDK 2.3.2 has a dependency with UIWebView:
```
HyBid
         U _OBJC_CLASS_$_UIWebView
                 U _OBJC_CLASS_$_UIWebView
```

Causing the following automatic app review rejection:
TMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

**Comment by wimbledon** [comment]
@can-soykarafakili

**Comment by wimbledon** [comment]
After I downgraded to version 2.2.1, the problem went away.

**Comment by can-soykarafakili** [comment]
Hey @wimbledon !!

Thanks for pointing out that issue... And I'm sorry for the trouble that it caused. 😢 We're working on a hotfix right now and I'll share in here when we release it. 👍

**Comment by can-soykarafakili** [comment]
@wimbledon We've released a hotfix for that issue. You can find it [here](https://github.com/pubnative/pubnative-hybid-ios-sdk/releases/tag/2.3.3).

Thank you for you patience and have a good day!! 😃

**Comment by wimbledon** [comment]
Thank you, @can-soykarafakili!
