### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by mmguerras** [pubnative/pubnative-hybid-ios-sdk#322]
Only importing HyBid, when I build for a second time without doing Clean Build Folder before, I'm getting the following error

> Command PhaseScriptExecution failed with a nonzero exit code

> Executable is /Users/user/Library/Developer/Xcode/DerivedData/App-hbyjltogdwpgeabdecsjlhxlhvst/Build/Products/Debug-iphonesimulator/App.app/Frameworks/HyBid.framework/HyBid
Extracting x86_64 from HyBid
fatal error: lipo: input file (/Users/user/Library/Developer/Xcode/DerivedData/App-hbyjltogdwpgeabdecsjlhxlhvst/Build/Products/Debug-iphonesimulator/App.app/Frameworks/HyBid.framework/HyBid) must be a fat file when the -extract option is specified
Merging extracted architectures: x86_64
fatal error: lipo: can't open input file: /Users/user/Library/Developer/Xcode/DerivedData/App-hbyjltogdwpgeabdecsjlhxlhvst/Build/Products/Debug-iphonesimulator/App.app/Frameworks/HyBid.framework/HyBid-x86_64 (No such file or directory)
rm: /Users/user/Library/Developer/Xcode/DerivedData/App-hbyjltogdwpgeabdecsjlhxlhvst/Build/Products/Debug-iphonesimulator/App.app/Frameworks/HyBid.framework/HyBid-x86_64: No such file or directory
Replacing original executable with thinned version
mv: rename /Users/user/Library/Developer/Xcode/DerivedData/App-hbyjltogdwpgeabdecsjlhxlhvst/Build/Products/Debug-iphonesimulator/App.app/Frameworks/HyBid.framework/HyBid-merged to /Users/user/Library/Developer/Xcode/DerivedData/App-hbyjltogdwpgeabdecsjlhxlhvst/Build/Products/Debug-iphonesimulator/App.app/Frameworks/HyBid.framework/HyBid: No such file or directory

Xcode 12.4

**Comment by can-soykarafakili** [comment]
Hey @mmguerras can you provide a bit more information?

- Are you using cocoapods or drag & drop .xcframework for HyBid integration?

If you are using the drag & drop method, can you double check whether did you remove the Run Script under Build Phases explained in [here](https://github.com/pubnative/pubnative-hybid-ios-sdk/wiki/Setup-HyBid)

**Comment by mmguerras** [comment]
- Cocoapods
- 2.4.2, but it happened in previous versions

**Comment by can-soykarafakili** [comment]
Did you check whether the Run script is still there in your project in Build Settings? Because some of the logs there seems to have the exact wording from our old Run script. 🤔

**Comment by mmguerras** [comment]
@can-soykarafakili Removing the old Run script works perfectly. 

Thanks!

**Comment by can-soykarafakili** [comment]
You're welcome @mmguerras !! 😄 

Stay safe & healthy!!
