### ISSUE TITLE
Version 2.9.1 is missing on Cocoapods

### ISSUE THREAD

**Issue by Yuri-Soomla** [pubnative/pubnative-hybid-ios-sdk#324]
pod 'HyBid', '2.9.1' failed 
https://github.com/CocoaPods/Specs/tree/master/Specs/a/b/d/HyBid

**Comment by Yuri-Soomla** [comment]
@eros902002 Please see this issue

**Comment by eros902002** [comment]
Hi @Yuri-Soomla . Thanks for the report. Indeed something seemed to have failed with the pod trunk publication. It's fixed now : )

**Comment by Yuri-Soomla** [comment]
@eros902002 Thanks
