### ISSUE TITLE
Version 2.10.0 is missing on Cocoapods

### ISSUE THREAD

**Issue by Yuri-Soomla** [pubnative/pubnative-hybid-ios-sdk#325]
Hey, 
For some reason version 2.10.0 is missing on Cocoapods - 
https://github.com/CocoaPods/Specs/tree/master/Specs/a/b/d/HyBid

**Comment by Yuri-Soomla** [comment]
@eros902002 Please check this issue

**Comment by can-soykarafakili** [comment]
Hey @Yuri-Soomla 

`v: 2.10.0` is already released on Cocoapods as well. The reason why you couldn't see the desired version is probably the indexing working a bit slow.

If you type `pod install --repo-update` on the terminal, it should install the latest version.

For more information you can check our [Sample App](https://github.com/pubnative/hybid-ios-standalone-demo) that has the HyBid iOS SDK `v: 2.10.0`.
