### ISSUE TITLE
Crash with HyBid 3.0.2

### ISSUE THREAD

**Issue by Yurish-IL** [pubnative/pubnative-hybid-ios-sdk#333]
Hi Guys, 
I just updated HyBid to the latest version 3.0.2 and am experiencing a crash related to Atom and Swift. This crash does not occur with version 3.0.1.

Xcode version 15.4
Device - iPhone XR, 17.5.1

`referenced from: <5B12930D-70E8-3E30-8891-5ACA2727A153> /private/var/containers/Bundle/Application/BB2DA57F-971E-4A54-86E3-B97D8C597290/DemoApp.app/Frameworks/HyBid.framework/HyBid
 Reason: tried: '/usr/lib/swift/ATOM.framework/ATOM' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/ATOM.framework/ATOM' (no such file), '/private/var/containers/Bundle/Application/BB2DA57F-971E-4A54-86E3-B97D8C597290/DemoApp.app/Frameworks/ATOM.framework/ATOM' (no such file), '/private/var/containers/Bundle/Application/BB2DA57F-971E-4A54-86E3-B97D8C597290/DemoApp.app/Frameworks/HyBid.framework/Frameworks/ATOM.framework/ATOM' (no such file), '/usr/lib/swift/ATOM.framework/ATOM' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/ATOM.framework/ATOM' (no such file), '/private/var/containers/Bundle/Application/BB2DA57F-971E-4A54-86E3-B97D8C597290/DemoApp.app/Frameworks/ATOM.framework/ATOM' (no such file), '/private/var/containers/Bundle/Application/BB2DA57F-971E-4A54-86E3-B97D8C597290/DemoApp.app/Frameworks/ATOM.framework/ATOM' (no such file), '/usr/lib/swift/ATOM.framework/ATOM' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/ATOM.framework/ATOM' (no such file), '/private/var/containers/Bundle/Application/BB2DA57F-971E-4A54-86E3-B97D8C597290/DemoApp.app/Frameworks/ATOM.framework/ATOM' (no such file), '/private/var/containers/Bundle/Application/BB2DA57F-971E-4A54-86E3-B97D8C597290/DemoApp.app/Frameworks/ATOM.framework/ATOM' (no such file)`

Thanks

**Comment by eros902002** [comment]
Thanks for the report @Yurish-IL. We're checking this with the highest priority. Will get back to you ASAP

**Comment by faresbh** [comment]
@Yurish-IL Can you share with us your integration setup? Did you use Drag and Drop or Cocoapods?

**Comment by Yurish-IL** [comment]
Hi @faresbh 
Im using Cocoapods.
` pod 'HyBid', '3.0.2'`

**Comment by faresbh** [comment]
Thanks @Yurish-IL , Would be very helpful if you could provide us with a simple demo project showing the issue.

**Comment by Yurish-IL** [comment]
Hi @faresbh,
Sorry, but our company's Privacy and Security policies prevent me from sending you any internal testers, apps, or documents.
